### PR TITLE
spider and tests for Atlanta BeltLine Inc.

### PR DESCRIPTION
**Pull request by rhetr**
## Summary

**Issue:** #5 

## Checklist

All checks are run in [GitHub Actions](https://github.com/features/actions). You'll be able to see the results of the checks at the bottom of the pull request page after it's been opened, and you can click on any of the specific checks listed to see the output of each step and debug failures.

- [ ] Tests are implemented
- [ ] All tests are passing
- [ ] Style checks run (see [documentation](https://cityscrapers.org/docs/development/) for more details)
- [ ] Style checks are passing
- [ ] Code comments from template removed

## Questions
- this relies on `EventsCalendarSpider` being merged into `city_scrapers_core` (https://github.com/City-Bureau/city-scrapers-core/pull/17), the checks will fail until then
- the classifications need to be confirmed
- i might need to rename the spider if it conflicts with the other two scrapers for beltline?

### CODE REVIEW

**Comment by jpt-c** [comment]
the upstream fix is merged if you want to update this PR 👍

**Comment by rhetr** [comment]
I must be overlooking something...not sure what i have to update exactly? I thought that once `EventsCalendarSpider` got merged into `city_scrapers_core` the checks would work, but it looks like it still isn't being found:

```
E   ImportError: cannot import name 'EventsCalendarSpider' from 'city_scrapers_core.spiders' (/home/runner/work/city-scrapers-atl/city-scrapers-atl/.venv/lib/python3.8/site-packages/city_scrapers_core/spiders/__init__.py)
```

**Comment by jpt-c** [comment]
Thanks, I'll take a look!

**Comment by jpt-c** [comment]
confirmed working locally w/ a fresh venv 👍

**Pull request merged**
